version: "3.9"

#поднимает PostgreSQL, Redis, NATS

services:

  postgres:
    image: postgres:16-alpine
    container_name: jobmarket_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobmarket
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust    # ← добавь эту строку
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d jobmarket"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: jobmarket_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  nats:
    image: nats:2-alpine
    container_name: jobmarket_nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream", "--store_dir=/data"]
    volumes:
      - nats_data:/data

volumes:
  pg_data:
  redis_data:
  nats_data: